# Copyright (c) 2020 Liam McSherry
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

image: Visual Studio 2019

configuration: Release

branches:
    only:
        - master
        - stable

pull_requests.do_not_increment_build_number: true


install:
    - ps: dotnet tool install -g BenchmarkDotNet.Tool

before_build:
    - cmd: nuget restore

artifacts:
    - path: .\McSherry.SemanticVersioning\bin\Release\*\McSherry.SemanticVersioning.dll

test_script:
    - dotnet test McSherry.SemanticVersioning.Testing\McSherry.SemanticVersioning.Testing.csproj --no-build

# Only parsing benchmarks are run as they can complete relatively quickly. Others
# can be run as and when required as they take significantly longer.
after_test:
    - ps: dotnet benchmark .\McSherry.SemanticVersioning.Benchmarking\bin\Release\netcoreapp2.1\McSherry.SemanticVersioning.Benchmarking.dll --filter *ParsingBenchmarks.*